//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.20 at 09:47:24 PM EEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.springframework.org/schema/web-services", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package lt.eif.viko.l.mackevicius.BookStoreClient.generated_class;
